function analysisBanner(){return db.analysis?`<div class="note"><b>已完成現有紀錄探索分析。</b> 同日重複、revision、無效病歷與身分矛盾已另行處理；下方為原始列概覽。<p><button class="primary" data-go="analysis">查看清理後 ${db.analysis.flow.primary} 位分析 →</button> <button data-go="ai">AI 量測工具查核 →</button></p></div>`:'';}
const followStat=s=>s.n?`${s.n} 位 · ${num(s.median)}（${num(s.q1)}–${num(s.q3)}）`:'0 位 · 缺測';
const caseButton=id=>`<button data-analysis-patient="${esc(id)}">${esc(id)} ↗</button>`;
function recordAnalysis(){
 const a=db.analysis;if(!a)return panel('分析尚未載入','請重新登入以取得新快照。');const s=a.summary,f=a.flow;
 const tags={postop_improvement_phrase:'術後改善句',neck_pain_mention:'頸痛相關詞',numbness_mention:'麻木相關詞',weakness_mention:'無力／肌力相關詞',lumbar_or_leg_context:'腰／腿部脈絡',swallow_voice_mention:'吞嚥／聲帶相關詞',vas_numeric_mention:'VAS 數字',ndi_numeric_mention:'NDI 數字',joa_numeric_mention:'JOA／mJOA 數字',adjacent_segment_mention:'相鄰節段用語',horner_mention:'Horner 用語'};
 return title('SOURCE-GROUNDED · EXPLORATORY','現有紀錄與門診分析','計數單位：病人。這是資料清理後的描述性探索，臨床納排與結局裁定仍待老師確認。')+
 `<div class="cards">${metric('主描述群',f.primary,'344 位原始名單，348 列手術')}${metric('術後診療正文',s.clinical.n,`缺 ${f.primary-s.clinical.n} 位；已排除純領藥`)}${metric('術後 X 光',s.imaging.n,`缺 ${f.primary-s.imaging.n} 位；尚未量測`)}${metric('兩年動態片＋術前片',s.pairedDynamic24,'18–30 月窗口；僅候選，尚待判讀姿勢')}</div>`+
 panel('現在可以說的結果',`<ol><li><b>追蹤資料尚不均衡：</b>診療正文末次日期中位數 ${num(s.clinical.median)} 月、X 光 ${num(s.imaging.median)} 月，分母不同。兩者皆有 ${s.clinicalAndImaging} 位；看診正文可能以腰、膝或其他問題為主，不能等同已評估 ADR 結局。</li><li><b>品牌比較須控制追蹤時間：</b>Prestige 的診療正文追蹤中位數 33.1 月，ProDisc-C 9.3 月；品牌使用年份也不同。目前不適合用各組末次紀錄直接比較效果。</li><li><b>Hybrid 比例高：</b>${s.hybrid}/${s.n}（${(100*s.hybrid/s.n).toFixed(1)}%）原表含合併融合描述，應先分層。品牌仍依原表文字分類，僅 ${s.sameDayReport}/${s.n} 有同日手術正文。</li><li><b>兩年影像主結局需縮小範圍：</b>${s.dynamic24Window} 位有 18–30 月動態候選研究，${s.pairedDynamic24} 位另有術前 90 日內動態候選；Mobi-C 此窗口目前為 0，無法作完整的跨品牌兩年 ROM 比較。</li></ol>`)+
 panel('清理流程與原始證據',`<p>${f.rawRows} 原始列 → 合併 ${f.duplicateExcessRows} 列同日重複 → 345 個日期事件、${f.roster} 位病人。按病人排除 3 位非 ADR、3 位無效病歷、3 位 revision、1 位身分矛盾，保留 ${f.primary} 位候選。原始列全部保留。</p><details><summary>展開需核對的病例與來源</summary>${a.duplicateGroups.map(x=>`<p>${caseButton(x.patient)} ${x.date}：同日重複；${x.sourceRows.map(esc).join(' / ')}</p>`).join('')}${a.audit.map(x=>`<p>${caseButton(x.patient)} ${esc(x.detail)}</p>`).join('')}${a.revisionRecords.map(x=>`<p>${caseButton(x.patient)} ${x.date}：revision 原句</p><pre>${esc(x.quote)}</pre>`).join('')}</details>`)+
 panel('品牌、年齡與追蹤分布',`<p class="muted">連續值：中位數（第 25–75 百分位）；月份按日數 ÷ 30.4375。追蹤欄先列可用 N，未測者不填 0。品牌拼字／型號待確認，未把 VIVO 名稱自行合併。</p><div class="scroll"><table><thead><tr><th>品牌候選</th><th>N</th><th>年齡</th><th>女 / 男</th><th>Hybrid</th><th>手術年</th><th>診療正文 N · 月</th><th>X 光 N · 月</th><th>兩年動態 / 術前配對</th></tr></thead><tbody>${a.brands.map(b=>`<tr><td>${esc(b.brand)}</td><td>${b.n}</td><td>${num(b.age.median)}（${num(b.age.q1)}–${num(b.age.q3)}）</td><td>${b.sex.F||0} / ${b.sex.M||0}</td><td>${b.hybrid}</td><td>${b.yearRange.join('–')}</td><td>${followStat(b.clinical)}</td><td>${followStat(b.imaging)}</td><td>${b.dynamic24Window} / ${b.pairedDynamic24}</td></tr>`).join('')}</tbody></table></div><p class="muted">全群年齡 ${num(s.age.median)}（${num(s.age.q1)}–${num(s.age.q3)}）歲，女／男各 ${s.sex.F} 位。診療正文末次日期 ≥24 月 ${s.clinicalGE24} 位；X 光末次日期 ≥24 月 ${s.imagingGE24} 位。末次超過兩年不代表兩年窗口有片。</p>`)+
 panel('門診文字：能抽取什麼',`<p>原始 ${a.notes.allSources} 份門診來源中，${a.notes.refillOnly} 份只有慢性處方領藥，${a.notes.clinicalText} 份含診療正文。主描述群中 ${s.clinical.n} 位有手術日之後的診療正文。</p><p><b>找到改善、持續／復發症狀與聲帶事件的文字線索，但沒有可直接配對分析的標準化量表。</b>以下為詞句檢索覆蓋，包含歷史、否定與其他部位，不能解讀為症狀盛行率、成功率或併發症率。</p><div class="scroll"><table><thead><tr><th>檢索標記</th><th>含該文字的正文數 / 可檢索正文</th></tr></thead><tbody>${a.notes.mentions.map(x=>`<tr><td>${tags[x.tag]}</td><td>${x.n} / ${x.denominator}</td></tr>`).join('')}</tbody></table></div><p class="muted">未命中 NDI／JOA 規則不等於來源絕對沒有量表。VAS 常混有舊史、肩腰腿症狀或 mm／0–10 量尺；目前不計算 ΔVAS、MCID。</p>`)+
 panel('已核對原句的臨床例子',`<p class="muted">目的性選取的 9 個例子，用於展示判讀問題；不是完整結局裁定，不能據此估率。日期為本次取得的門診來源日期，文內歷史事件另辨識。</p>${a.clinicalExamples.map(x=>`<details><summary>${esc(x.patient)} · ${x.date} · ${esc(x.category)}</summary><p>${caseButton(x.patient)} ${esc(x.interpretation)}</p><blockquote>${esc(x.quote)}</blockquote><small class="muted">${esc(x.sourceId)} · ${esc(x.status)}</small></details>`).join('')}`)+
 panel('逐病人追蹤與候選配對',`<details><summary>展開 ${s.n} 位清理後候選，點研究編號可回到影像與原文</summary><div class="scroll"><table><thead><tr><th>病例</th><th>手術</th><th>品牌</th><th>診療正文末次 / 月</th><th>X 光末次 / 月</th><th>兩年動態候選</th></tr></thead><tbody>${a.patientRows.map(r=>`<tr><td>${caseButton(r.patient)}</td><td>${r.date}</td><td>${esc(r.brand)}</td><td>${r.clinicalDate||'缺'} / ${num(r.clinicalMonths)}</td><td>${r.imagingDate||'缺'} / ${num(r.imagingMonths)}</td><td>${r.pairedDynamic24?'術前＋兩年':r.dynamic24Window?'僅兩年':'未取得'}</td></tr>`).join('')}</tbody></table></div></details>`)+
 panel('分析邊界與下一步',`<ul>${a.limitations.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><p>建議先核對 27 位配對候選的影像品質及原始手術日期，再由兩位評讀者量 ROM／Cobb／HO；補齊相同時間窗的頸臂 VAS、NDI 後，才做臨床與影像關聯。</p><p class="muted">來源快照 ${esc(a.sourceSnapshot)}；分析 ${esc(a.generatedAt)}。資料 hash <small style="overflow-wrap:anywhere">${a.sourceDatasetSha256}</small></p><button data-go="ai">查看 AI 量測工具查核 →</button>`);
}
function aiTools(){return title('AI X-RAY · EVIDENCE CHECK','AI 量測工具查核','公開來源初查：2026-09-28。本輪已完成公開分割模型的本機批次試跑；請看「AI 全片試測」。臨床準確度仍未驗證。')+
 panel('結論',`<p><b>有 AI 輔助頸椎量測研究，也有可取得權重的分割原型；目前沒有找到能直接替本研究完成 ADR 術後 ROM、Cobb 與 modified McAfee／Mehren 的已驗證整套技能。</b></p><p>近期研究最貼近 C2–7 Cobb；公開分割程式可作為後續開發起點。正式結果仍需保存端點、原始影像與人工修正紀錄。</p>`)+
 panel('工具與適用範圍',`<div class="scroll"><table><thead><tr><th>工具／論文</th><th>實際功能</th><th>公開程度</th><th>本案判斷</th></tr></thead><tbody>
 <tr><td><a href="https://www.nature.com/articles/s41746-026-02455-2" target="_blank" rel="noreferrer">Kang 等，npj Digital Medicine 2026</a></td><td>C2／C7 關鍵點、C2–7 lordosis、slope、SVA；外部驗證 C2–7 角度 MAE 約 2.6°。</td><td>程式須向通訊作者合理請求；非直接可安裝套件。</td><td>最貼近 global Cobb，但不能把論文準確度外推到 ADR 節段 ROM／HO。</td></tr>
 <tr><td><a href="https://pmc.ncbi.nlm.nih.gov/articles/PMC9641900/" target="_blank" rel="noreferrer">HRNet SIRM，2022</a></td><td>頸椎 flexion／neutral／extension 的節段旋轉活動量測。</td><td>已發表研究；本次未確認公開可直接部署的完整權重。</td><td>研究排除既往頸椎手術、C7 遮蔽等情況；不適合直接宣稱 ADR 術後準確。</td></tr>
 <tr><td><a href="https://github.com/nievsky/Cervical-Spine-Segmentation-App" target="_blank" rel="noreferrer">Cervical Spine Segmentation App</a></td><td>側位 X 光 C2–C7 分割，可作端點偵測的前處理。</td><td>有 best.pt（約 20.5 MB）；2026-06 更新。GitHub 未標出 license；README 使用 CUDA。</td><td>最接近可下載原型，但分割不等於 Cobb／ROM；需確認授權、Mac 執行及金屬植入物表現。</td></tr>
 <tr><td><a href="https://github.com/shunxneuro/OC2_object-detection" target="_blank" rel="noreferrer">OC2 object detection</a></td><td>YOLOv7／Gradio，O–C2 角度及端點。</td><td>MIT 程式；repo 未附 best.pt，須另取得權重。</td><td>測 O–C2，與 ADR 的 C2–7／節段角度不同；適合作介面參考。</td></tr>
 <tr><td><a href="https://github.com/abhisuri97/SpineTK" target="_blank" rel="noreferrer">SpineTK</a>／<a href="https://github.com/zhibaishouheilab/CervAI-X" target="_blank" rel="noreferrer">CervAI-X</a></td><td>前者為脊柱側彎 AP Cobb；後者為 MRI。</td><td>公開程式庫。</td><td>投照或模態與本題不符，不直接採用。</td></tr>
 </tbody></table></div><p class="muted">本次未找到公開且已驗證用於 ADR 後 modified McAfee／Mehren 自動分級的工具；這是本次搜尋結果，並非不存在相關研究的證明。</p>`)+
 panel('本研究可採用的驗證路徑',`<ol><li>先固定端點與角度定義；使用 SSD 原始解析影像，記錄姿勢、節段、左右與影像品質。</li><li>先從不同品牌、hybrid、C7 遮蔽程度抽取約 30 位配對病例作試驗；實際可用數須閱片確認。</li><li>AI 只提出分割／端點；評讀者確認終板後才計算有符號 Cobb，flexion／extension 角度差計算 ROM。</li><li>兩位評讀者獨立量測作參照；報 MAE、ICC、Bland–Altman 與失敗率。HO 另由影像與活動度判讀，報 weighted kappa。</li><li>驗證前所有 AI 輸出留在草稿，不併入正式結果；完整保存版本、來源 hash 與修正歷程。</li></ol><p>目前網站已有四點兩線夾角工具，可先進行人工評讀。此次模型在本機離線運算，未把病例影像傳送到外部 AI 服務；權重未重新發布。</p><button data-go="patients">進入病例閱片 →</button>`);}
